from sqlalchemy.orm import Session
import models, schemas


def get_user(db: Session, user_id: int):
    return db.query(models.User).filter(models.User.id == user_id).first()


def get_user_by_email(db: Session, email: str):
    return db.query(models.User).filter(models.User.email == email).first()


def create_user(db: Session, user: schemas.UserCreate):
    # 1. Create ORM model instance
    fake_hashed_password = user.password + "notreallyhashed"
    db_user = models.User(email=user.email, hashed_password=fake_hashed_password)

    # 2. Add to session
    db.add(db_user)

    # 3. Commit (save to DB)
    db.commit()

    # 4. Refresh (get the new ID generated by the DB)
    db.refresh(db_user)

    return db_user